Add control for two cameras
FRC2357-SystemMeltdown/FRC-2019 pull request #30
Opened 2019-02-19 22:25 UTC by thesprintingturtle

Add controls for two cameras with source switching.

2019-02-21 23:06 UTC, coderkevin requested changes
There are some changes needed for this PR.

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/modes/DriverFailsafeMode.java
> +import edu.wpi.cscore.UsbCamera;
These aren't used here and shouldn't be included.
Neither should the blank lines below.

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/Subsystems/VisionSub.java
> +  public enum LEDMode {
Can we call this "LimelightLEDMode"? Since it doesn't apply to the USB camera?

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/Subsystems/VisionSub.java
> +    private LEDMode(int value) {
This is ambiguous with setLEDMode below. I think this needs to be clearer.

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/DriveTab.java
> +    private VideoSource USBCamera0;
Can we name this `usbCamera` instead? We only have one, and variable names should start with lower case.

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/ShuffleboardController.java
> +    driveTab.periodic();
We should probably only be calling the period of the current tab. We should set an instance variable of the current tab, and just call `currentTab.periodic()`

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/TestTab.java
> +    videoSourcesInitialized = false;
I think I'd rather have a single widget for each video source. And more than just "initialized" would be useful. Maybe "off", "on", and "streaming" or something like that.

2019-02-21 23:06 UTC, coderkevin commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/TestTab.java
> +      // if(source.getName() == "limelight") {
Let's not check in commented code.

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/Subsystems/VisionSub.java
> +    private LEDMode(int value) {
This is a constructor for the enum so we can set the values to match the limelight API. This whole enum should be in its own file.

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/DriveTab.java
> +        if(limelight != null) {
Is this check correct? It seems like you only want to search for the camera if you haven't found it yet.

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/DriveTab.java
> +                if(source.getName() == "limelight") {
Have you tested this? I couldn't get the limelight to show up in this list when I tested it. The CameraServer instance reported the limelight to Shuffleboard, but it didn't seem to make a VideoSource for it. I might not have waited long enough after boot, though.

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/DriveTab.java
> +        for(VideoSource source : VideoSource.enumerateSources()) {
My comments in periodic() apply here as well. If this code is necessary it shouldn't be repeated.

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/TestTab.java
> +    if(!videoSourcesInitialized && VideoSource.enumerateSources().length >= 2) {
This was test code that I hadn't gotten working...

2019-02-22 00:21 UTC, shadwstalkr commented on 2019RobotCode/src/main/java/frc/robot/shuffleboard/DriveTab.java
> +                if(source.getName() == "USB Camera 0") {
Is this block necessary? You already have the source instance for this camera in VisionSub.webcam.

2019-03-08 04:22 UTC, coderkevin commented
This PR isn't really applicable anymore since we started plugging the scoring cam into the limelight.
We can look back here for led settings though.

2019-03-08 04:22 UTC, closed without merging

2019-03-08 04:22 UTC, coderkevin commented
There's no way to programmatically add the camera view to the tab, so we just have to add it manually. Code won't help us on that.